apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-root-containers
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: check-runasnonroot
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                  - argocd
                  - kyverno
                  - trivy-system
      validate:
        message: "DEVSECOPS WARNING: Running containers as ROOT is strictly prohibited on this cluster! Set ‘runAsNonRoot: true’ in your manifest. (CIS Benchmark compliance)"
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true